networks:
  servicos:
    external:
      name: servicos

services:
  mongodb:
    image: mongo:4.4.6
    environment:
       - MONGO_INITDB_ROOT_USERNAME={{ secrets.mongodb.user }}
       - MONGO_INITDB_ROOT_PASSWORD={{ secrets.mongodb.pass }}
    healthcheck:
      test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - servicos
    ports:
      - "27017:27017"

  mesa-auth:
    image: "{{ docker_account }}/mesa-auth:2023.3.2"
    container_name: "auth"
    restart: always
    environment:
        - SELF_NAME=auth
        - CLIENT_NAME={{ client_name | default('client') }}
        - AUTH_SECRET={{ secrets.auth.secret }}
        - ENCRYPTION_KEY=ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg=
        - DB_HOST=mongodb
        - DB_USER={{ secrets.mongodb.user }}
        - DB_PASS={{ secrets.mongodb.pass }}
    networks:
      - servicos
    depends_on:
      - mongodb
    ports:
      - "5000:5000"

